### ISSUE TITLE
[Feature] 邀请白名单功能

### ISSUE THREAD

**Issue by mon030** [ApliNi/IpacWhitelist#12]
允许已拥有白名单或拥有此权限的玩家邀请其他玩家加入白名单，并且记录邀请者和受邀请者的id。

**Comment by ApliNi** [comment]
也就是玩家被添加到白名单时记录操作者的信息?

**Comment by mon030** [comment]
是的



---Original---
From: ***@***.***&gt;
Sent at: 2024年3月1日(Fri) Early Morning4:52
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ApliNi/IpacWhitelist] [Feature] 邀请白名单功能 (Issue #12)




 
也就是玩家被添加到白名单时记录操作者的信息?

**Comment by ApliNi** [comment]
抱歉来晚了, 这类功能已经准备实现, 目前有一个测试版可以使用

![image](https://github.com/ApliNi/IpacWhitelist/assets/59365724/58b86da6-f10d-44d9-8ee4-5b7fdf4356b2)

https://github.com/ApliNi/IpacWhitelist/releases/tag/v4.1.1-rc1
