### ISSUE TITLE
添加papi变量支持

### ISSUE THREAD

**Issue by TATyKeFei** [ApliNi/IpacWhitelist#16]
能否添加几个变量支持
比如%wl_player_ban_time_left%返回剩余封禁时长
%wl_player_ban_time%返回被封禁的时间
%wl_player_stats%返回白名单状态
%wl_player_ban_reason%返回封禁原因

**Comment by ApliNi** [comment]
关于返回封禁相关信息, 这个插件并没有支持按时间封禁账户以及添加原因, 建议使用其他 ban 插件

不过白名单状态是没问题的, 你看这样可以吗?

**Comment by TATyKeFei** [comment]
> 关于返回封禁相关信息, 这个插件并没有支持按时间封禁账户以及添加原因, 建议使用其他 ban 插件
> 
> 不过白名单状态是没问题的, 你看这样可以吗?

都没问题，不过要是能把这些功能都做出来就更好了(o-ωｑ)

**Comment by ApliNi** [comment]
https://github.com/ApliNi/IpacWhitelist/releases/tag/v4.1.1-rc4

久等了, 这一个测试版本需要测试 PAPI 支持, 如果您有时间帮我测试是最好的 (因为我并不会使用 PAPI)

添加了两个变量:
- `iwl_player_type_name` - 显示当前玩家类型的显示名称, 名称可配置
- `iwl_player_type` - 显示当前玩家类型的内部名称

**Comment by TATyKeFei** [comment]
> https://github.com/ApliNi/IpacWhitelist/releases/tag/v4.1.1-rc4
> 
> 久等了, 这一个测试版本需要测试 PAPI 支持, 如果您有时间帮我测试是最好的 (因为我并不会使用 PAPI)
> 
> 添加了两个变量:
> 
> * `iwl_player_type_name` - 显示当前玩家类型的显示名称, 名称可配置
> * `iwl_player_type` - 显示当前玩家类型的内部名称
> 
> (这里的 Type 应该就是玩家类型

这个版本有个问题，装上后我进服客户端提示无法连接此服务器，服务端日志只有个显示ip来源。换回之前的版本就好了
![image](https://github.com/ApliNi/IpacWhitelist/assets/125815900/f3893be7-e833-4a44-9ed2-55aae607626a)
![image](https://github.com/ApliNi/IpacWhitelist/assets/125815900/5758b33d-3fd0-4c06-aab8-2bc68c9ae603)

另外这个变量似乎并没有起效
![image](https://github.com/ApliNi/IpacWhitelist/assets/125815900/cdda9df5-bb92-4e39-837e-9640f3504427)

**Comment by ApliNi** [comment]
ok, 请等我研究一下, 另外我知道 papi 怎么测试了

**Comment by ApliNi** [comment]
https://github.com/ApliNi/IpacWhitelist/releases/tag/4.1.1-rc5

这个版本测试好了 PAPI 功能, 并且添加了新的功能:
- `%iwl_player_type%` - 显示当前玩家类型的内部名称
- `%iwl_player_type(playerName|playerUUID)%` - 显示指定玩家类型的内部名称
- `%iwl_player_type_name%` - 显示当前玩家类型的显示名称, 名称可配置
- `%iwl_player_type_name(playerName|playerUUID)%` - 显示指定玩家类型的显示名称, 名称可配置
```
> papi parse ApliNi %iwl_player_type%
[08:18:17 INFO]: NOT
> papi parse ApliNi %iwl_player_type(NELVC)%
[08:18:23 INFO]: WHITE
```

---

对于无法连接至服务器我不认为是这个插件导致的, 因为我没有测试出这个问题, 并且在你提供的日志中没有这个插件主动踢出玩家的消息或是错误日志

**Comment by TATyKeFei** [comment]
感谢，我知道为什么会弹出无法连接服务器了，我之前用的v3版本删了下配置文件重新生成就好了
我试了下变量都正常，但是什么都没做插件突然就炸了(Purpur1.20.4)，删掉所有配置文件都没有用重启服务器都没有用
这个版本稳定性似乎不是很好，我还是先老老实实用v3版本吧💧💧💧

![image](https://github.com/ApliNi/IpacWhitelist/assets/125815900/ffca5ef4-3488-482f-a686-41c4d27d6616)

**Comment by ApliNi** [comment]
我怀疑这和插件加载顺序有关系, 这通常出现在插件比较多的服务器上, 如果您可以提供包含此错误的完整启动日志, 我应该能解决它... 😥

**Comment by TATyKeFei** [comment]
[2024-05-07-6.log.gz](https://github.com/ApliNi/IpacWhitelist/files/15234024/2024-05-07-6.log.gz)

看起来好像是和eco插件打架了?
![image](https://github.com/ApliNi/IpacWhitelist/assets/125815900/949facf9-e2a3-4624-99f7-8a37d909388d)

**Comment by TATyKeFei** [comment]
不对，我把eco前置卸载了还是这样😭

**Comment by ApliNi** [comment]
看上去只是因为没用关闭 `hook.AuthMe`

```yaml
# 连接到其他插件
hook:
  AuthMe: false    # 离线登录插件
```

**Comment by TATyKeFei** [comment]
感谢! 现在功能正常了
没啥大问题😋
