### ISSUE TITLE
封禁原因显示自定义  以及封禁倒计时

### ISSUE THREAD

**Issue by hyh-Forever** [ApliNi/IpacWhitelist#21]
如题，希望支持当已被封禁的玩家尝试加入服务器，看到一条可以自定义的断开消息
另外，希望支持限时封禁，比如封禁48小时，48小时之后自动解除封禁状态，在此期间登录会看到配置的断开消息和倒计时（希望可通过配置文件来配置是否显示）

**Comment by ApliNi** [comment]
感谢您的支持, 您提到的这个需求更推荐使用专用的封禁插件, 这个白名单插件更主要的目的是实现白名单和参观账户功能.
