### ISSUE TITLE
管理或已存在的玩家进服没在白名单

### ISSUE THREAD

**Issue by on-dream** [ApliNi/IpacWhitelist#28]
我觉得应该改改xwx
因为这个插件是服务器后面装的
问题大xwx

**Comment by on-dream** [comment]
（authme已注册玩家添加白名单）

**Comment by on-dream** [comment]
我不会弄xwx求教xwx

**Comment by ApliNi** [comment]
如果你的 AuthMe 使用 SQLite 存储, 就使用任意一个数据库软件 (如 DB Browser SQLite) 打开它, 从表中复制出所有用户名 (一行一个), 接下来使用类似 VSCode 的文本编辑器将正则表达式 `^` 替换为 `/wl add ` 可得到所有指令, 然后全选复制并粘贴到服务器控制台即可. *也可使用白名单插件的导出格式*
