### ISSUE TITLE
玩家名字带空格无法添加白名单

### ISSUE THREAD

**Issue by TATyKeFei** [ApliNi/IpacWhitelist#9]
我服来了个基岩玩家，他的名字带空格叫"doting fire"。
我用`/wl add doting fire`时他却显示了指令帮助并没有给添加白名单

**Comment by ApliNi** [comment]
有很多其他插件也不支持这样的名称，应该使用 Geyser 或者 Floodgate 的功能将空格转换为下划线 "_"

**Comment by ApliNi** [comment]
```
# Should spaces be replaced with '_' in bedrock usernames?
replace-spaces: true
```
在这里, 记得配置好 Floodgate 与 Geyser 的连接, 不然可能无法使用
